### ISSUE TITLE
Generate # sign character?

### ISSUE THREAD

**Issue by gabbaca** [eladnava/material-letter-icons#3]
Is it possible to generate the '#' sign character?

**Comment by eladnava** [comment]
@gabbaca Absolutely! =) Just add it at [config.js#L5](https://github.com/eladnava/material-letter-icons/blob/master/config.js#L5) and run the generator.

**Comment by gabbaca** [comment]
I just tried the following and got an error: 
config.js: // Characters to generate, as string
        characters: '#0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

[Error: Unable to load the source file.]

Otherwise it works if I leave it out.

**Comment by eladnava** [comment]
@gabbaca It's because the `svg2png` package is having trouble reading from `dist/svgs/#.svg` due to the special character -- you can modify the code so it outputs the letter's char code instead in [generator.js:L63](https://github.com/eladnava/material-letter-icons/blob/master/generator.js#L63):

``` js
var outputSVGPath = __dirname + '/' + config.dist.svg.outputPath + letter.charCodeAt(0) + '.svg';
var outputPNGPath = __dirname + '/' + config.dist.png.outputPath + letter.charCodeAt(0) + '.png';
```

**Comment by gabbaca** [comment]
Awesome, thanks for the quick reply that worked.

**Comment by eladnava** [comment]
@gabbaca My pleasure! =)

**Comment by eladnava** [comment]
I think that we should add support for this automatically.

In cases where the character is not a valid filename character (there are ways to detect this), we can simply write it out with the char code instead. I'll add code that does this in a few days.

**Comment by eladnava** [comment]
@gabbaca It has been implemented.

**Comment by gabbaca** [comment]
Cool thank you
