### ISSUE TITLE
Generate fails on Windows

### ISSUE THREAD

**Issue by tno2007** [eladnava/material-letter-icons#5]
When I run the generate command: 
`material-letter-icons generate --chars '$#@'`

on Windows I get the following error. It's not write-access denied related as I am running the command as Administrator. 

![windows](https://cloud.githubusercontent.com/assets/6169249/15632435/69862c4a-2591-11e6-8ea1-803a408f3aed.png)

On Linux (Centos) it works perfectly.

**Comment by eladnava** [comment]
@tno2007 can you please try generating an icon for an alphanumeric character to rule out the symbols causing an issue?

```
material-letter-icons generate --chars 'A'
```

**Comment by tno2007** [comment]
The issue still persists. I have tried with every other alphabet letter as well.

![screenshot 2016-05-29 14 07 41](https://cloud.githubusercontent.com/assets/6169249/15633171/c76bdb60-25a6-11e6-9560-4f00910ad111.png)

**Comment by eladnava** [comment]
I tried to generate icons on Windows 7 and it worked. Unfortunately, I don't have a newer Windows to test on.

This does seem like it's an issue with the underlying PhantomJS library used by [svg2png](https://www.npmjs.com/package/svg2png), so the fix would probably have to be made there and not in `material-letter-icons`.

**Comment by eladnava** [comment]
I've created an issue in the `svg2png` GitHub repo:
https://github.com/domenic/svg2png/issues/47

Closing this until we find a solution.

**Comment by Havret** [comment]
I got the same error. :( Is there any chance to fix it?

**Comment by eladnava** [comment]
@Havret Can you try cloning `material-letter-icons` locally and updating the `svg2png` dependency to its latest version? It may fix the issue.

Then, try generating icons again by running `node index.js`?

I unfortunately no longer have access to a Windows computer, so I can't test this for myself.

**Comment by eladnava** [comment]
This may have been fixed by the updated `svg2png` in the latest release. Please reopen if issue still exists.
