### ISSUE TITLE
Not working with mac

### ISSUE THREAD

**Issue by imromec** [eladnava/material-letter-icons#6]
> RoMeC:iconss RoMeC$ sudo material-letter-icons generate --chars '$#@'
Password:
info material-letter-icons Generating icon: $
ERR! Icon generator failed Error: Command failed: /usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/node_modules/phantomjs/lib/phantom/bin/phantomjs /usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/lib/converter.js /usr/local/lib/node_modules/material-letter-icons/lib/../dist/svg/ASCII-36.svg /usr/local/lib/node_modules/material-letter-icons/lib/../dist/png/ASCII-36.png {"width":512,"height":512}
ERR! Icon generator failed 
ERR! Icon generator failed     at ChildProcess.exithandler (child_process.js:213:12)
ERR! Icon generator failed     at emitTwo (events.js:87:13)
ERR! Icon generator failed     at ChildProcess.emit (events.js:172:7)
ERR! Icon generator failed     at maybeClose (internal/child_process.js:829:16)
ERR! Icon generator failed     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! Icon generator failed     at emitOne (events.js:77:13)
ERR! Icon generator failed     at Socket.emit (events.js:169:7)
ERR! Icon generator failed     at Pipe._onclose (net.js:486:12)
ERR! Icon generator failed  { [Error: Command failed: /usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/node_modules/phantomjs/lib/phantom/bin/phantomjs /usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/lib/converter.js /usr/local/lib/node_modules/material-letter-icons/lib/../dist/svg/ASCII-36.svg /usr/local/lib/node_modules/material-letter-icons/lib/../dist/png/ASCII-36.png {"width":512,"height":512}
ERR! Icon generator failed ]
ERR! Icon generator failed   killed: false,
ERR! Icon generator failed   code: null,
ERR! Icon generator failed   signal: 'SIGSEGV',
ERR! Icon generator failed   cmd: '/usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/node_modules/phantomjs/lib/phantom/bin/phantomjs /usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/lib/converter.js /usr/local/lib/node_modules/material-letter-icons/lib/../dist/svg/ASCII-36.svg /usr/local/lib/node_modules/material-letter-icons/lib/../dist/png/ASCII-36.png {"width":512,"height":512}' }

**Comment by eladnava** [comment]
Seems to be an upstream issue:
https://github.com/Medium/phantomjs/issues/402

The `phantomjs` binary throws a `SIGSEGV` on your machine for some reason.

**Comment by rahulgovind** [comment]
An older version of svg2png is being used which in turn also uses an older version of phantomjs. 

Fixed the error by copying a newer version of phantomjs in the respective directory which I guess would be `/usr/local/lib/node_modules/material-letter-icons/node_modules/svg2png/node_modules/phantomjs/lib/phantom/bin` in your case. 

For some reason, I couldn't get material-letter-icons to work on newer versions of svg2png.

**Comment by eladnava** [comment]
@rahulgovind Were you also receiving the `SIGSEGV` on your Mac workstation? What is your OS version?

**Comment by rahulgovind** [comment]
> Were you also receiving the SIGSEGV on your Mac workstation? 

I was

> What is your OS version?

macOS 10.12.3

**Comment by eladnava** [comment]
Seems PhantomJS 1.9 is not compatible with Sierra.

Fixed by updating `svg2png` and its API in https://github.com/eladnava/material-letter-icons/commit/f1cbe6d7a466eec4b3a3fc89f38e125747437e3c.

**Comment by eladnava** [comment]
Seems PhantomJS 1.9 is not compatible with macOS Sierra. Fixed by updating `svg2png` in commit https://github.com/eladnava/material-letter-icons/commit/f1cbe6d7a466eec4b3a3fc89f38e125747437e3c. 

Please try updating `material-letter-icons` to `1.0.8` and try again.
