### ISSUE TITLE
SVG text is misaligned in Firefox and IE

### ISSUE THREAD

**Issue by chadokruse** [eladnava/material-letter-icons#7]
This is likely out of scope of the project as I'm using the SVGs directly, but just an FYI, text is top-aligned on Firefox and IE (see screenshot below).

The fix appears to be using `dominant-baseline="central"` instead of `alignment-baseline"central"`. I have not yet tested this on IE, but [this SO question](https://stackoverflow.com/questions/12250403/vertical-alignment-of-text-element-in-svg) may prove useful for others who stumble upon this in the future.

Thanks for creating this project 👊

![screenshot-firefox-v-chrome](https://user-images.githubusercontent.com/314653/27460956-e4d1f1f4-577c-11e7-8768-9146f6d73a51.png)

**Comment by eladnava** [comment]
Hi @chadokruse,
Thanks for reporting this and glad that you like the project!

Would you like to submit a PR with this fix provided it does not alter the intended behavior of the package? 👍

**Comment by chadokruse** [comment]
While changing `alignment-baseline="central"` to `dominant-baseline="central"` fixes things on Firefox, good 'ol IE appears to require an [ugly hack using dy](https://stackoverflow.com/a/29089222/1944104):

`<text x="255" y="255" dy="0.35em" text-anchor="middle" fill="#fff"...</text>`

Happy to send over a PR to adjust the SVGs, but it's starting to feel a bit out of scope? The real fix seems to simply use the PNGs instead of SVGs for cross-browser compatibility.

*****
Original - works on Webkit browsers
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="532" height="532" viewBox="0 0 512 512">
    <circle cx="255" cy="255" r="230" fill="#00bfa5" />
    <text x="255" y="246" alignment-baseline="central" text-anchor="middle" fill="#fff" font-size="275" font-weight="100" font-family="Roboto">0</text>
</svg>
```
Adjusted - works on Webkit + Firefox
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="532" height="532" viewBox="0 0 512 512">
    <circle cx="255" cy="255" r="230" fill="#00bfa5" />
    <text x="255" y="246" dominant-baseline="central" text-anchor="middle" fill="#fff" font-size="275" font-weight="100" font-family="Roboto">0</text>
</svg>
```
Hack - works on all browsers
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="532" height="532" viewBox="0 0 512 512">
    <circle cx="255" cy="255" r="230" fill="#00bfa5" />
    <text x="255" y="255" dy="0.35em" text-anchor="middle" fill="#fff" font-size="275" font-weight="100" font-family="Roboto">0</text>
</svg>
```

**Comment by eladnava** [comment]
The icons are pre-generated in `.png` format within the `dist/` directory:
https://github.com/eladnava/material-letter-icons/tree/master/dist/png

Does that help?

**Comment by chadokruse** [comment]
Thanks @eladnava, I'm all good so closing this issue.
